version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  php:
    build: .
    depends_on:
      - mysql
    env_file: .env
    entrypoint: ['php', 'artisan', 'serve', '--host=0.0.0.0']
