name: CI/CD

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
      - run: composer install --no-progress --no-interaction
      - uses: atymic/deployer-php-action@0.2.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.DEPLOY_SSH_KNOWN_HOSTS }}
      - run: php artisan deploy
